
sbmanager:

  ###### GLOBAL #####

  prefix: "&a&lSKYBLOCK &f»"

  #### ADMINCHAT ####

  acprefix: "&7[&c&lAC&7]"
  acnickcolor: "&c"
  actextcolor: "&7»"
  ytmessage: "&7Zapraszamy na &c&lLIVE&7:"
  hoverytmessage: "&7Kliknij tutaj, aby otworzyć!"


